# Generated by Django 5.0.1 on 2024-01-15 18:40

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="content", field=froala_editor.fields.FroalaField(),
        ),
    ]
